#!/bin/sh
#
#    10-header - create the header of the MOTD

# Source os-release for PRETTY_NAME (works on Void, Ubuntu, etc.)
[ -r /etc/os-release ] && . /etc/os-release

VAMOS_VERSION=$(cat /VERSION)
GIT_HASH=$(head -1 /BUILD 2>/dev/null | cut -c1-7)

if [ -n "$GIT_HASH" ]; then
	VAMOS_DESCRIPTION="$VAMOS_VERSION ($GIT_HASH)"
else
	VAMOS_DESCRIPTION="$VAMOS_VERSION"
fi

printf "Welcome to vamOS v%s\n" "$VAMOS_DESCRIPTION"
printf "Based on %s (%s %s %s)\n" "$PRETTY_NAME" "$(uname -o)" "$(uname -r)" "$(uname -m)"
