#!/bin/sh

cat << 'EOF'

Here are some useful commands:
  Enter the tmux session where the comma service runs
  (note: tmux prefix key has been configured to backtick)
    └── tmux a

  Install packages
    └── sudo xbps-install -S <pkg>

  Install Python packages
    └── pip install <pkg>

When modifying vamOS, keep in mind that the system partition isn't
particularly large. /data/ is the largest partition, and unlike the
rest of the partitions, it will persist across vamOS updates.

Want a clean slate? Reflash vamOS with https://flash.comma.ai.
EOF
