name: build system

concurrency:
  group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.system-builder'
      - 'build_system.sh'
      - 'userspace/**'
      - 'VERSION'
      - '.github/workflows/build-system.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'Dockerfile.system-builder'
      - 'build_system.sh'
      - 'userspace/**'
      - 'VERSION'
      - '.github/workflows/build-system.yml'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: build system image
        run: ./build_system.sh

      - name: upload system.img
        uses: actions/upload-artifact@v4
        with:
          name: system.img
          path: output/system.img
